"""
MediaAsset entity.

Provider-independent representation of one discovered visual asset. Every
VideoSourcePort adapter must translate its provider's response into this
shape before it leaves the adapter — no Pexels-specific (or, later,
Pixabay/Mixkit-specific) response object is ever allowed to reach
VideoSearchService or anything above it.

``id`` vs ``provider_asset_id`` (Sprint 3.1): ``id`` is the globally unique,
provider-prefixed identifier used everywhere in this codebase as the
asset's identity (e.g. "pexels:2499611") — safe to use as a storage key
component or a cross-provider dict key without collisions.
``provider_asset_id`` is the raw, provider-native id with no prefix (e.g.
"2499611") — the form a provider's own API expects back if this asset ever
needs to be re-fetched, deep-linked, or compared against that provider's
native records. Neither is generated by the domain layer via uuid4, unlike
Script/VoiceTrack: both come from the provider, because throwing away the
provider's own identity would lose exactly the information a later sprint
(re-fetching, deep-linking, dedup) would need back.

``local_path`` is None until VideoSearchService downloads and persists the
asset via StoragePort — see ``with_local_path``. ``score`` is unused until
semantic ranking is introduced in a later sprint.

``metadata`` (Sprint 3.1): an open, provider-agnostic bag for attributes no
provider search API returns today but a later AI Vision analysis step
could compute per-asset — e.g. dominant_colors, motion_level, people_count,
indoor_outdoor, camera_angle, detected_objects. Deliberately untyped
(``dict[str, Any]``) and empty by default: this sprint does not populate
or interpret it. Keeping it a plain dict rather than a dedicated
value object avoids committing to a schema before the sprint that actually
needs one exists to define it — same reasoning as deferring a CachePort in
Sprint 2.1 until a second consumer of caching actually appears.
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Any, Optional


@dataclass(frozen=True)
class MediaAsset:
    id: str
    provider: str
    provider_asset_id: str = ""
    media_type: str = "video"
    original_url: str = ""
    thumbnail_url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    duration_seconds: Optional[float] = None
    fps: Optional[float] = None
    tags: list[str] = field(default_factory=list)
    attribution: str = ""
    license: str = ""
    local_path: Optional[str] = None
    score: Optional[float] = None
    # Reserved for a future AI Vision analysis step (Sprint 6+ scene
    # matching). Empty and unread by anything in this sprint.
    metadata: dict[str, Any] = field(default_factory=dict)

    def with_local_path(self, local_path: str) -> "MediaAsset":
        """Return a copy of this asset with ``local_path`` set.

        MediaAsset is frozen like every other domain object in this
        codebase; VideoSearchService calls this after StoragePort.save()
        succeeds, rather than reconstructing a MediaAsset field-by-field
        and risking one being copied incorrectly or forgotten.
        """
        return replace(self, local_path=local_path)

    def to_dict(self) -> dict:
        """Export a plain-dict shape for CLI/JSON output or a future
        downstream consumer (e.g. a Scene Planning service). Mirrors
        VoiceTrack.to_dict()."""
        return {
            "id": self.id,
            "provider": self.provider,
            "provider_asset_id": self.provider_asset_id,
            "media_type": self.media_type,
            "local_path": self.local_path,
            "original_url": self.original_url,
            "thumbnail_url": self.thumbnail_url,
            "width": self.width,
            "height": self.height,
            "duration_seconds": self.duration_seconds,
            "fps": self.fps,
            "tags": self.tags,
            "attribution": self.attribution,
            "license": self.license,
            "score": self.score,
            "metadata": self.metadata,
        }
