import re

with open("server.py", "r") as f:
    code = f.read()

injection = """
@app.post("/api/publish/{job_id}")
async def api_publish(job_id: str, platform: str = Form(...)):
    try:
        from infrastructure.repositories.local_json_run_repository import LocalJsonRunRepository
        repo = LocalJsonRunRepository(PROJECT_ROOT / ".selma_runs")
        run = await repo.get_by_id(job_id)

        # In a real scenario we extract the final path from the run manifest. Here we mock finding a video file path.
        video_path = PROJECT_ROOT / "output" / "final.mp4"

        # Just for testing if it doesn't exist, create a dummy
        import os
        os.makedirs(video_path.parent, exist_ok=True)
        if not video_path.exists():
            with open(video_path, "wb") as f:
                f.write(b"dummy video data")

        from infrastructure.providers.publish.omnichannel_upload_provider import OmnichannelUploadProvider
        uploader = OmnichannelUploadProvider()

        result_id = await uploader.upload_video(
            platform=platform,
            video_path=str(video_path),
            title=f"Selma AI Gen Video - {job_id[:8]}",
            description="Auto-generated by SELMA Dream Machine",
            tags=["AI", "Shorts", "Generated"]
        )

        return JSONResponse({"status": "success", "platform": platform, "platform_id": result_id})
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)

@app.post("/api/generate")"""

code = code.replace("@app.post(\"/api/generate\")", injection)

with open("server.py", "w") as f:
    f.write(code)
