import React from "react";
import {interpolate} from "remotion";
import type {SceneMode} from "./types";

const C={ink:"#06101c",white:"#f7fbff",yellow:"#ffd42a",cyan:"#58e9ff",red:"#ff425f",green:"#57f0b1"};
const Box:React.FC<{x:number;y:number;w?:number;label:string;color?:string;delay?:number;p:number;bad?:boolean}>=({x,y,w=250,label,color=C.cyan,delay=0,p,bad})=>{const s=interpolate(p,[delay,delay+.12],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div style={{position:"absolute",left:x,top:y,width:w,padding:"18px 16px",background:"rgba(4,12,22,.92)",border:`3px solid ${bad?C.red:color}`,boxShadow:`0 0 28px ${bad?C.red:color}35`,color:C.white,font:"900 25px Arial",textAlign:"center",opacity:s,transform:`scale(${.9+.1*s})`}}>{label}</div>};
const Link:React.FC<{x:number;y:number;w:number;bad?:boolean;p:number;delay?:number}>=({x,y,w,bad,p,delay=0})=><div style={{position:"absolute",left:x,top:y,width:w*interpolate(p,[delay,delay+.15],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),height:6,background:bad?`repeating-linear-gradient(90deg,${C.red} 0 15px,transparent 15px 28px)`:C.cyan,boxShadow:`0 0 14px ${bad?C.red:C.cyan}`,transformOrigin:"left"}}/>;

export const Diagram:React.FC<{mode:SceneMode;p:number;local:number}>=({mode,p,local})=>{
 if(mode==="network"||mode==="recovery")return <div style={{position:"absolute",left:585,top:300,width:1210,height:470}}><Box x={0} y={150} label="TÜRKİYE" p={p}/><Link x={250} y={190} w={210} p={p} delay={.07}/><Box x={455} y={60} label="KARA FİBER" p={p} delay={.12}/><Box x={455} y={250} label="DENİZALTI" p={p} delay={.16}/><Link x={705} y={100} w={180} bad p={p} delay={.23}/><Link x={705} y={290} w={180} p={p} delay={.27}/><Box x={880} y={150} label="DÜNYA" p={p} delay={.32}/></div>;
 if(mode==="local")return <div style={{position:"absolute",left:570,top:285,width:1240,height:500}}><Box x={0} y={130} label="BİLGİSAYAR" p={p}/><Link x={250} y={173} w={180} p={p}/><Box x={425} y={130} label="YEREL SUNUCU ✓" color={C.green} p={p} delay={.12}/><Link x={675} y={173} w={180} bad p={p} delay={.24}/><Box x={850} y={130} label="BULUT ✕" bad p={p} delay={.3}/><div style={{position:"absolute",left:385,top:300,color:C.green,font:"1000 36px Arial"}}>DİJİTAL ADA ÇALIŞIYOR</div></div>;
 if(mode==="payment")return <div style={{position:"absolute",left:620,top:290,width:1120,height:500,display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>{[["KASA A","YEDEK HAT","ONAY ✓",C.green],["KASA B","BAĞLANTI YOK","RED ✕",C.red]].map((row,i)=><div key={row[0]} style={{padding:28,background:"rgba(4,12,22,.9)",border:`3px solid ${row[3]}`,boxShadow:`0 0 30px ${row[3]}30`,transform:`translateY(${Math.sin(local/500+i)*5}px)`}}><div style={{color:C.white,font:"1000 37px Arial"}}>{row[0]}</div><div style={{color:"#aebdca",font:"800 25px Arial",marginTop:25}}>{row[1]}</div><div style={{color:row[3],font:"1000 54px Arial",marginTop:35}}>{row[2]}</div></div>)}</div>;
 if(mode==="gps")return <div style={{position:"absolute",left:660,top:275,width:1050,height:540}}><div style={{position:"absolute",left:420,top:0,font:"1000 55px Arial",color:C.cyan}}>GPS UYDUSU</div><div style={{position:"absolute",left:500,top:85,width:6,height:270,background:`linear-gradient(${C.cyan},transparent)`,transform:"rotate(22deg)"}}/><Box x={160} y={350} label="MAVİ NOKTA ✓" color={C.green} p={p}/><Box x={600} y={350} label="CANLI TRAFİK ✕" bad p={p} delay={.2}/></div>;
 if(mode==="calls")return <div style={{position:"absolute",left:680,top:285,width:990,height:510}}><Box x={0} y={165} label="TELEFON" p={p}/><Link x={250} y={207} w={180} p={p}/><Box x={425} y={165} label="BAZ İSTASYONU" p={p} delay={.1}/><Link x={675} y={207} w={160} p={p} delay={.2}/><Box x={830} y={165} w={140} label="112" color={C.red} p={p} delay={.25}/><div style={{position:"absolute",left:330,top:320,color:C.yellow,font:"900 31px Arial"}}>İNTERNET DEĞİL • TELEFON ŞEBEKESİ</div></div>;
 if(mode==="checklist")return <div style={{position:"absolute",left:620,top:270,width:1080,display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:16}}>{["ÇEVRİM DIŞI HARİTA","PİLLİ RADYO","MAKUL NAKİT","GÜÇ BANKASI","KÂĞIT NUMARALAR","BULUŞMA NOKTASI"].map((t,i)=><div key={t} style={{padding:"21px 24px",background:i===0?C.green:"rgba(4,12,22,.93)",color:i===0?C.ink:C.white,borderLeft:`7px solid ${C.green}`,font:"1000 29px Arial",opacity:interpolate(p,[i*.055,i*.055+.1],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),transform:`translateX(${interpolate(p,[i*.055,i*.055+.1],[35,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}px)`}}>✓ {t}</div>)}</div>;
 return null;
};
