import React from "react";
import {Easing, interpolate} from "remotion";
import type {SceneMode} from "./types";

const C={ink:"#07101c",white:"#f8fbff",muted:"#9fb0c0",yellow:"#ffd42a",cyan:"#58e9ff",red:"#ff425f",green:"#57f0b1",purple:"#b48cff",orange:"#ff9d45"};
const enter=(p:number,d=0)=>interpolate(p,[d,d+.13],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)});
const Panel:React.FC<{children:React.ReactNode;style?:React.CSSProperties}>=({children,style})=><div style={{background:"rgba(3,10,18,.91)",border:"1px solid rgba(255,255,255,.15)",boxShadow:"0 20px 48px rgba(0,0,0,.42)",...style}}>{children}</div>;

const Timeline:React.FC<{local:number;accent:string}>=({local,accent})=>{const hours=["0","1","3","6","9","12","16","20","24"];const progress=Math.min(1,local/78000);return <div style={{position:"absolute",left:145,right:145,top:500}}><div style={{height:12,background:"rgba(255,255,255,.18)",borderRadius:20}}><div style={{height:"100%",width:`${progress*100}%`,background:accent,boxShadow:`0 0 25px ${accent}`,borderRadius:20}}/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:22}}>{hours.map((h,i)=><div key={h} style={{color:i/hours.length<progress?C.white:C.muted,font:"1000 29px Arial"}}>{h}<span style={{fontSize:15}}> SA</span></div>)}</div></div>};

const SignalBars:React.FC<{local:number}>=({local})=><div style={{position:"absolute",right:260,top:210,width:760,height:570,display:"flex",alignItems:"end",gap:35}}>{[1,2,3,4,5].map((n,i)=><div key={n} style={{width:110,height:100+i*86,background:i<4?C.cyan:"rgba(255,255,255,.15)",boxShadow:i<4?`0 0 28px ${C.cyan}`:"none",opacity:.92}}/>)}<div style={{position:"absolute",left:0,right:0,bottom:180,color:C.red,font:"1000 92px Arial",textAlign:"center",textShadow:"0 6px 30px #000"}}>İNTERNET ✕</div></div>;

const RouteRedundancy:React.FC<{local:number}>=({local})=>{const pulse=(local%4200)/4200;const routes=[{top:245,color:C.cyan,label:"KARA FİBERİ"},{top:405,color:C.yellow,label:"DENİZALTI HATTI"},{top:565,color:C.green,label:"YEDEK ROTA"}];return <div style={{position:"absolute",left:600,top:160,width:1150,height:700}}><div style={{position:"absolute",left:0,top:315,width:150,height:150,borderRadius:"50%",display:"grid",placeItems:"center",background:C.white,color:C.ink,font:"1000 28px Arial"}}>TR</div><div style={{position:"absolute",right:0,top:315,width:150,height:150,borderRadius:"50%",display:"grid",placeItems:"center",background:C.white,color:C.ink,font:"1000 28px Arial"}}>DÜNYA</div>{routes.map((r,i)=><React.Fragment key={r.label}><div style={{position:"absolute",left:150,right:150,top:r.top,height:8,background:`linear-gradient(90deg,${r.color},${i===1?C.red:r.color})`,opacity:i===1?.45:1}}/><div style={{position:"absolute",left:140+(pulse*820),top:r.top-13,width:34,height:34,borderRadius:"50%",background:r.color,boxShadow:`0 0 25px ${r.color}`}}/><div style={{position:"absolute",left:420,top:r.top-52,color:r.color,font:"1000 24px Arial"}}>{i===1?"HASAR • TRAFİK YÖN DEĞİŞTİRİR":r.label}</div></React.Fragment>)}</div>};

const PaymentFlow:React.FC<{local:number}>=({local})=>{const p=(local%17000)/17000;const labels=["KART","POS","BANKA","ONAY"];return <div style={{position:"absolute",left:610,top:255,width:1120,height:560}}>{labels.map((x,i)=><React.Fragment key={x}><div style={{position:"absolute",left:i*285,top:165,width:220,padding:"28px 12px",border:`3px solid ${i===3?C.green:C.yellow}`,background:C.ink,color:C.white,font:"1000 34px Arial",textAlign:"center",opacity:enter(p,i*.14)}}>{x}</div>{i<3&&<div style={{position:"absolute",left:i*285+220,top:207,width:65,height:7,background:i===2&&p>.75?C.red:C.yellow}}/>}</React.Fragment>)}<div style={{position:"absolute",left:515,top:320,color:p>.75?C.red:C.green,font:"1000 58px Arial"}}>{p>.75?"BAĞLANTI YOK":"İŞLEM İLERLİYOR"}</div></div>};

const MapGrid:React.FC<{local:number}>=({local})=>{const pulse=(Math.sin(local/500)+1)/2;return <div style={{position:"absolute",left:600,top:195,width:1170,height:670,background:"linear-gradient(135deg,#09243a,#07101c)",overflow:"hidden",border:"1px solid rgba(88,233,255,.35)"}}>{Array.from({length:10}).map((_,i)=><div key={`v${i}`} style={{position:"absolute",left:i*130,top:0,bottom:0,width:2,background:"rgba(88,233,255,.16)"}}/>)}{Array.from({length:7}).map((_,i)=><div key={`h${i}`} style={{position:"absolute",top:i*105,left:0,right:0,height:2,background:"rgba(88,233,255,.16)"}}/>)}<div style={{position:"absolute",left:510,top:280,width:36,height:36,borderRadius:"50%",background:C.cyan,boxShadow:`0 0 ${35+pulse*45}px ${C.cyan}`}}/><div style={{position:"absolute",left:400,top:350,color:C.white,font:"1000 42px Arial"}}>KONUM ✓</div><div style={{position:"absolute",right:45,top:55,padding:"15px 20px",background:C.red,color:C.white,font:"1000 29px Arial"}}>CANLI TRAFİK ✕</div></div>};

const CallQueue:React.FC<{local:number}>=({local})=>{const value=Math.min(999,Math.floor(local/75));return <div style={{position:"absolute",left:650,top:235,width:1050,height:610}}><div style={{font:"1000 120px Arial",color:C.red}}>112</div><div style={{marginTop:20,color:C.white,font:"1000 44px Arial"}}>ÇAĞRI YOĞUNLUĞU</div><div style={{marginTop:35,height:42,background:"rgba(255,255,255,.15)"}}><div style={{height:"100%",width:`${Math.min(100,30+local/900)}%`,background:`linear-gradient(90deg,${C.yellow},${C.red})`}}/></div><div style={{marginTop:30,display:"flex",justifyContent:"space-between",font:"900 30px Arial",color:C.muted}}><span>ŞEBEKE AYAKTA</span><span>{value} BEKLEYEN</span></div><div style={{marginTop:70,color:C.cyan,font:"1000 32px Arial"}}>İNTERNET DEĞİL • TELEFON ŞEBEKESİ</div></div>};

const NewsSplit:React.FC<{local:number}>=({local})=><div style={{position:"absolute",left:560,top:220,width:1220,height:650,display:"grid",gridTemplateColumns:"1fr 1fr",gap:18}}><Panel style={{padding:35,borderTop:`10px solid ${C.green}`}}><div style={{font:"1000 34px Arial",color:C.green}}>DOĞRULANMIŞ YAYIN</div><div style={{marginTop:35,font:"900 50px Arial",color:C.white}}>RADYO<br/>TELEVİZYON<br/>RESMÎ SMS</div></Panel><Panel style={{padding:35,borderTop:`10px solid ${C.red}`}}><div style={{font:"1000 34px Arial",color:C.red}}>SÖYLENTİ ZİNCİRİ</div>{["BİRİNDEN DUYDUM","BAŞKA ŞEHİRDE DE...","RESMÎ AÇIKLAMA DİYORLAR"].map((x,i)=><div key={x} style={{marginTop:24,padding:17,background:"rgba(255,66,95,.12)",color:C.white,font:"900 28px Arial",translate:`${Math.sin(local/600+i)*8}px 0`}}>{x}</div>)}</Panel></div>;

const SupplyChain:React.FC<{local:number}>=({local})=>{const labels=["DEPO","KAMYON","MAĞAZA","KASA"];return <div style={{position:"absolute",left:570,top:310,width:1230,display:"flex",gap:44,alignItems:"center"}}>{labels.map((x,i)=><React.Fragment key={x}><div style={{width:220,height:220,borderRadius:i===1?"50%":22,display:"grid",placeItems:"center",background:i===2?C.orange:C.ink,border:`4px solid ${C.orange}`,color:i===2?C.ink:C.white,font:"1000 34px Arial",translate:`0 ${Math.sin(local/700+i)*9}px`}}>{x}</div>{i<3&&<div style={{font:"1000 65px Arial",color:i===1?C.red:C.orange}}>{i===1?"✕":"→"}</div>}</React.Fragment>)}</div>};

const CriticalRings:React.FC<{local:number}>=({local})=>{const rings=[["KRİTİK CİHAZ",C.green,170],["YEREL AĞ",C.cyan,270],["BULUT / TEDARİK",C.red,380]] as const;return <div style={{position:"absolute",left:790,top:145,width:800,height:800}}>{rings.map(([label,color,size],i)=><div key={label} style={{position:"absolute",left:400-size,top:400-size,width:size*2,height:size*2,borderRadius:"50%",border:`8px solid ${color}`,boxShadow:`0 0 25px ${color}30`,display:"grid",placeItems:"start center",paddingTop:22+i*14,color,font:"1000 27px Arial",rotate:`${Math.sin(local/1300+i)*2}deg`}}>{label}</div>)}</div>};

const RecoveryDashboard:React.FC<{local:number}>=({local})=>{const items=["FİBER","ROTA","ENERJİ","VERİ MERKEZİ"];const cycle=local%25000;return <div style={{position:"absolute",left:600,top:230,width:1160,display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:18}}>{items.map((x,i)=>{const ok=cycle>6500+i*3800;const blocked=i===3&&cycle>17500;const color=blocked?C.yellow:ok?C.green:C.red;return <Panel key={x} style={{padding:30,borderLeft:`10px solid ${color}`}}><div style={{color:C.white,font:"1000 37px Arial"}}>{x}</div><div style={{marginTop:18,color,font:"1000 29px Arial"}}>{blocked?"SINIRLI KAPASİTE":ok?"YEDEK DEVREDE ✓":"KONTROL EDİLİYOR"}</div></Panel>})}</div>};

const OutroChoice:React.FC<{local:number}>=({local})=>{const p=(Math.sin(local/700)+1)/2;return <div style={{position:"absolute",left:610,top:245,width:1130,display:"grid",gridTemplateColumns:"1fr 1fr",gap:30}}><Panel style={{height:450,padding:38,borderTop:`12px solid ${C.yellow}`,transform:`translateY(${p*8}px)`}}><div style={{font:"1000 32px Arial",color:C.muted}}>SONRAKİ DENEY</div><div style={{marginTop:60,font:"1000 68px/.95 Arial",color:C.white}}>ELEKTRİK<br/>KESİLİRSE?</div><div style={{marginTop:54,font:"1000 29px Arial",color:C.yellow}}>YORUMA: ELEKTRİK</div></Panel><Panel style={{height:450,padding:38,borderTop:`12px solid ${C.cyan}`,transform:`translateY(${(1-p)*8}px)`}}><div style={{font:"1000 32px Arial",color:C.muted}}>SONRAKİ DENEY</div><div style={{marginTop:60,font:"1000 68px/.95 Arial",color:C.white}}>GPS<br/>DURURSA?</div><div style={{marginTop:54,font:"1000 29px Arial",color:C.cyan}}>YORUMA: GPS</div></Panel></div>};

export const VisualSystem:React.FC<{mode:SceneMode;local:number;accent:string;sceneId:string}>=({mode,local,accent,sceneId})=>{
 if(mode==="hook")return <Timeline local={local} accent={accent}/>;
 if(mode==="network")return sceneId==="rules"?<RouteRedundancy local={local}/>:<SignalBars local={local}/>;
 if(mode==="payment")return <PaymentFlow local={local}/>;
 if(mode==="gps")return <MapGrid local={local}/>;
 if(mode==="calls")return <CallQueue local={local}/>;
 if(mode==="news")return <NewsSplit local={local}/>;
 if(mode==="logistics")return <SupplyChain local={local}/>;
 if(mode==="critical")return <CriticalRings local={local}/>;
 if(mode==="evening")return <Timeline local={local} accent={accent}/>;
 if(mode==="recovery")return <RecoveryDashboard local={local}/>;
 if(mode==="outro")return <OutroChoice local={local}/>;
 return null;
};
